name: Coverage

on:
  push:
    paths:
      - "CMakeLists.txt"
      - "codecov.yml"
      - "**/workflows/coverage.yml"
      - "**/cmake/**"
      - "**/modules/**"
      - "**/tests/**"
      - "!**/native/generated/**"
      - "!**/native/java*/**"
      - "!**/native/*_android.*"
      - "!**/native/*_apple.*"
      - "!**/native/*_emscripten.*"
      - "!**/native/*_ios.*"
      - "!**/native/*_mac.*"
      - "!**/native/*_wasm.*"
      - "!**/native/*_windows.*"
    branches:
      - "**"
  pull_request:
    paths:
      - "CMakeLists.txt"
      - "codecov.yml"
      - "**/workflows/coverage.yml"
      - "**/cmake/**"
      - "**/modules/**"
      - "**/tests/**"
      - "!**/native/generated/**"
      - "!**/native/java*/**"
      - "!**/native/*_android.*"
      - "!**/native/*_apple.*"
      - "!**/native/*_emscripten.*"
      - "!**/native/*_ios.*"
      - "!**/native/*_mac.*"
      - "!**/native/*_wasm.*"
      - "!**/native/*_windows.*"
    branches:
      - main
      - "dev/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  INSTALL_DEPS: >-
    libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype6-dev
    libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev
    libxrandr-dev libxrender-dev libglu1-mesa-dev libegl1-mesa-dev mesa-common-dev lcov
  IGNORE_ERRORS: "mismatch,gcov,source,negative,unused,empty,format,corrupt"

jobs:
  cpp-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y ${INSTALL_DEPS}

    - name: Configure CMake with Coverage
      run: |
        cmake ${{ github.workspace }} -B ${{ runner.workspace }}/build \
          -G "Ninja Multi-Config" \
          -DYUP_BUILD_TESTS=ON \
          -DYUP_BUILD_EXAMPLES=OFF \
          -DYUP_ENABLE_COVERAGE=ON \
          -DCMAKE_BUILD_TYPE=Debug

    - name: Build Tests
      working-directory: ${{ runner.workspace }}/build
      run: cmake --build . --config Debug --parallel 4 --target yup_tests

    - name: Clean Coverage Data
      working-directory: ${{ runner.workspace }}/build
      run: cmake --build . --target coverage_clean

    - name: Run C++ Tests
      working-directory: ${{ runner.workspace }}/build/tests/Debug
      run: ./yup_tests --gtest_output=xml:test_results.xml

    - name: Generate C++ Coverage Report
      working-directory: ${{ runner.workspace }}/build
      run: |
        mkdir -p coverage
        lcov --directory . --capture --output-file coverage/coverage.info --ignore-errors ${IGNORE_ERRORS}
        lcov -r coverage/coverage.info \
          "*/thirdparty/*" \
          "*/build/*" \
          "*/tests/*" \
          "*/usr/*" \
          "*/opt/*" \
          "*/CMakeFiles/*" \
          -o coverage/cpp.info --ignore-errors ${IGNORE_ERRORS}
        lcov --list coverage/cpp.info

    - name: Upload C++ Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: cpp-coverage
        path: ${{ runner.workspace }}/build/coverage/cpp.info

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: ${{ runner.workspace }}/build/tests/Debug/test_results.xml

  python-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup and install python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y lcov

    - name: Build Python Wheels and Run Python Tests
      uses: pypa/cibuildwheel@v3.0.0
      env:
        CIBW_ARCHS: x86_64
        CIBW_BUILD: cp311-manylinux_x86_64
        CIBW_TEST_SKIP: "*manylinux*"
        CIBW_DEBUG_TRACEBACK: TRUE
        CIBW_ENVIRONMENT: CIBW_DEBUG_TRACEBACK=TRUE YUP_ENABLE_COVERAGE=1
      with:
        package-dir: python

    - name: Upload Python Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: python-coverage
        path: wheelhouse/lcov.info

  combine-coverage:
    runs-on: ubuntu-latest
    needs: [cpp-coverage, python-coverage]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y lcov

    - name: Download C++ Coverage Report
      uses: actions/download-artifact@v4
      with:
        name: cpp-coverage
        path: coverage/

    - name: Download Python Coverage Report
      uses: actions/download-artifact@v4
      with:
        name: python-coverage
        path: coverage/

    - name: Combine Coverage Reports
      run: |
        lcov -r coverage/lcov.info "*/pybind11/*" -o coverage/python.info --ignore-errors ${IGNORE_ERRORS}
        lcov -a coverage/cpp.info -a coverage/python.info -o coverage/coverage_final.info --ignore-errors ${IGNORE_ERRORS}
        lcov --list coverage/coverage_final.info

    - name: Upload Combined Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/coverage_final.info
        name: overall-coverage
        fail_ci_if_error: false
        verbose: true

    - name: Upload Combined Coverage Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: combined-coverage-reports
        path: coverage/